// Quiz data for the first lecture (Blockchain Security)
// type: "single" | "multiple" | "text"
// - single/multiple: options = { a: "...", b: "..." }, correct = ["d"] or ["a", "c"]
// - text: answers = [accepted answers]; matching ignores case and spaces
// - image (optional): path to an image shown above the question

const quizData_01 = [
  {
    id: 1,
    type: "single",
    question: "What is the primary goal of Bitcoin?",
    options: {
      a: "create a currency that is issued and controlled by a central bank",
      b: "make payments faster than any credit card network",
      c: "allow banks to reverse and monitor all transactions",
      d: "realise a payment without a trusted third party",
    },
    correct: ["d"],
    explanation: "Bitcoin aims to be a decentralized digital currency that works without relying on a trusted third party such as a bank.",
  },
  {
    id: 2,
    type: "multiple",
    question: "What are the advantages of Bitcoin?",
    options: {
      a: "pseudonymity (users appear only under addresses)",
      b: "transactions can be reversed by a bank in case of fraud",
      c: "peer-to-peer transactions",
      d: "guaranteed stable value",
    },
    correct: ["a", "c"],
    explanation: "Payments are sent directly between peers without a financial institution, and users appear only under pseudonyms (addresses). Reversible transactions and a stable value are not features of Bitcoin.",
  },
  {
    id: 3,
    type: "multiple",
    question: "What are the disadvantages of Bitcoin?",
    options: {
      a: "it requires a central authority to approve every payment",
      b: "slow transaction processing",
      c: "vulnerable to hacking or forgotten passwords",
      d: "transactions can only be sent during bank opening hours",
      e: "high transaction fees",
    },
    correct: ["b", "c", "e"],
    explanation: "Transactions are grouped into blocks roughly every 10 minutes, so processing is slow. Whoever has the private key controls the coins, so a lost password or a hacked wallet can mean lost funds. Fees can be high. No central authority is involved, and Bitcoin runs around the clock.",
  },
  {
    id: 4,
    type: "text",
    question: "What are members of the Bitcoin network called?",
    answers: ["node", "nodes"],
    explanation: "Members of the network are called nodes. A node is a device running the Bitcoin software.",
  },
  {
    id: 5,
    type: "multiple",
    question: "What are some functionalities of nodes?",
    options: {
      a: "Mining",
      b: "Issuing government-backed currency",
      c: "Wallet",
      d: "Network routing",
      e: "Approving transactions as a central authority",
      f: "Storing the full blockchain",
    },
    correct: ["a", "c", "d", "f"],
    explanation: "All nodes are equal, but they may support different functionalities: network routing, wallet, mining and storing the full blockchain.",
  },
  {
    id: 6,
    type: "single",
    question: "TRUE or FALSE: Network routing is supported by any node of the Bitcoin network.",
    options: { a: "TRUE", b: "FALSE" },
    correct: ["a"],
    explanation: "Forwarding, validating and propagating transactions and blocks is supported by every node. Other functionalities such as mining are optional.",
  },
  {
    id: 7,
    type: "single",
    question: "A wallet is a ...",
    options: {
      a: "software realising one or more Bitcoin accounts",
      b: "database that stores the full blockchain",
      c: "bank account at a Bitcoin exchange",
      d: "device that stores bitcoins physically",
    },
    correct: ["a"],
    explanation: "A wallet is software through which a user manages keys and addresses and creates or signs transactions. Coins are recorded on the blockchain, not stored in the wallet.",
  },
  {
    id: 8,
    type: "multiple",
    question: "An address is a ...",
    options: {
      a: "private key used to sign transactions",
      b: "copy of the blockchain",
      c: "pseudonym",
      d: "set of numbers identifying the Bitcoin account",
    },
    correct: ["c", "d"],
    explanation: "Addresses are numbers that identify Bitcoin accounts and act as pseudonyms for users. One user can use many addresses.",
  },
  {
    id: 9,
    type: "multiple",
    question: "Miners:",
    options: {
      a: "add transactions to the blockchain",
      b: "achieve consensus",
      c: "issue wallets to new users",
      d: "store the private keys of all users",
    },
    correct: ["a", "b"],
    explanation: "Mining is essential for achieving consensus among the nodes about which data (transactions, blocks) is added to the blockchain.",
  },
  {
    id: 10,
    type: "single",
    question: "Full nodes are special in that:",
    options: {
      a: "they keep track of transactions not yet added to the blockchain",
      b: "they are connected to every other node in the network",
      c: "they keep track of the blockchain",
      d: "they are responsible for validating transactions",
    },
    correct: ["c"],
    explanation: "Full nodes store the complete blockchain. Validating and propagating transactions is done by every node, and nodes are not directly connected to all other nodes.",
  },
  {
    id: 11,
    type: "single",
    question: "If a new node wants to join the network, it can contact a:",
    options: {
      a: "full node",
      b: "miner",
      c: "seed node",
      d: "any node",
    },
    correct: ["c"],
    explanation: "A new node must discover at least one existing node. One option is seed nodes: long-running, stable nodes that are preinstalled in the Bitcoin software.",
  },
  {
    id: 12,
    type: "single",
    question: "What is the trade-off in choosing the number of peers?",
    options: {
      a: "too many peers: higher propagation delay",
      b: "too few peers: too many messages are sent around",
      c: "too many messages or higher propagation delay and lower connectivity",
      d: "too many peers: lower connectivity",
    },
    correct: ["c"],
    explanation: "A high number of peers means too many messages are sent around. A low number means higher propagation delay and lower connectivity.",
  },
  {
    id: 13,
    type: "single",
    question: "TRUE or FALSE: Users are anonymous.",
    options: { a: "TRUE", b: "FALSE" },
    correct: ["b"],
    explanation: "Users are pseudonymous. They appear under addresses, and the network topology may allow linking addresses to IP addresses, which can make users identifiable to some extent.",
  },
  {
    id: 14,
    type: "multiple",
    question: "Why are hash functions necessary?",
    options: {
      a: "to ensure accuracy and completeness of data",
      b: "to encrypt data so that nobody can read it",
      c: "to make users fully anonymous",
      d: "to prevent attackers from manipulating data",
    },
    correct: ["a", "d"],
    explanation: "Hash values are short fingerprints that allow checking efficiently whether a data copy is equal to the original, which protects integrity. Hash functions do not encrypt data.",
  },
  {
    id: 15,
    type: "single",
    question: "Evaluate if this formula of hash functions is correct: H: {0,1}* -> {0,1}^n",
    options: { a: "Correct", b: "Incorrect" },
    correct: ["a"],
    explanation: "A hash function maps bitstrings of arbitrary length ({0,1}*) to bitstrings of fixed length n ({0,1}^n). Typical values for n are 256 and 512.",
  },
  {
    id: 16,
    type: "single",
    question: "The hash function can be expressed as H: {0,1}* -> {0,1}^n. What does it mean?",
    options: {
      a: "bitstrings of fixed length are converted into bitstrings of arbitrary length",
      b: "bitstrings of arbitrary length are converted into bitstrings of the same length",
      c: "bitstrings of arbitrary length are converted into bitstrings of fixed length",
      d: "bitstrings of arbitrary length are encrypted into bitstrings that can be decrypted again",
    },
    correct: ["c"],
    explanation: "{0,1}* stands for bitstrings of any length, {0,1}^n for bitstrings of exactly n bits.",
  },
  {
    id: 17,
    type: "text",
    question: "Write down the general hash function formula.",
    answers: [
      "H: {0,1}* -> {0,1}^n",
      "H: {0,1}* → {0,1}^n",
      "{0,1}* -> {0,1}^n",
    ],
    explanation: "A hash function maps arbitrary-length bitstrings {0,1}* to fixed-length bitstrings {0,1}^n: H: {0,1}* -> {0,1}^n.",
  },
  {
    id: 18,
    type: "single",
    question: "The sender gives the hash value of the message to the receiver. What does the receiver check?",
    options: {
      a: "whether the message is encrypted",
      b: "he hashes the received message himself and checks whether the result matches the hash value he was given",
      c: "he decrypts the hash value to recover the original message",
      d: "he compares the message with the hash value character by character",
    },
    correct: ["b"],
    explanation: "The receiver computes h' = H(m') and accepts the message only if h = h'. If an attacker changed the message, the hashes differ.",
  },
  {
    id: 19,
    type: "multiple",
    question: "What is NOT a security requirement of hash functions?",
    options: {
      a: "collision resistance",
      b: "deterministic",
      c: "invertibility (the input can be easily computed from the hash)",
      d: "preimage resistance",
      e: "second-preimage resistance",
    },
    correct: ["b", "c"],
    explanation: "The three security requirements are collision resistance, preimage resistance and second-preimage resistance. \"Deterministic\" is part of the definition, not a security requirement. Easy invertibility would violate preimage resistance.",
  },
  {
    id: 20,
    type: "single",
    question: "Collision resistance means it should be hard to find two messages x and x' such that:",
    options: {
      a: "x = x' and H(x) = H(x')",
      b: "x ≠ x' and H(x) = H(x')",
      c: "x ≠ x' and H(x) ≠ H(x')",
      d: "x = x' and H(x) ≠ H(x')",
    },
    correct: ["b"],
    explanation: "A collision is two different messages with the same hash. The effort for finding one should be in O(2^(n/2)).",
  },
  {
    id: 21,
    type: "single",
    question: "Preimage resistance means: given a hash value h, it should be hard to find a message x such that:",
    options: {
      a: "H(x) ≠ h",
      b: "H(x) = x",
      c: "H(x) ≠ x",
      d: "H(x) = h",
    },
    correct: ["d"],
    explanation: "Such an x is called a preimage of h. The effort for finding one should be in O(2^n).",
  },
  {
    id: 22,
    type: "single",
    question: "Second-preimage resistance means: given a message x and its hash value h, it should be hard to find a message x' ≠ x such that:",
    options: {
      a: "H(x) = h",
      b: "H(x') = h",
      c: "H(x) ≠ h",
      d: "H(x') ≠ h",
    },
    correct: ["b"],
    explanation: "The attacker is given x and must find a different message with the same hash. The effort should be in O(2^n).",
  },
  {
    id: 23,
    type: "multiple",
    question: "What does the Random Oracle Model of hash functions say?",
    options: {
      a: "hash functions are completely unpredictable",
      b: "there are no shortcuts to computing the hash function",
      c: "knowing many hash values makes the next one easier to predict",
      d: "similar inputs always produce similar outputs",
    },
    correct: ["a", "b"],
    explanation: "H is idealised as a black box that seems to sample outputs randomly. To determine H(x), nothing is better than computing it, even if many other hash values are already known.",
  },
  {
    id: 24,
    type: "single",
    question: "What is 1 bitcoin (₿) in satoshis?",
    options: {
      a: "1,000",
      b: "1 million",
      c: "100 million",
      d: "1 billion",
    },
    correct: ["c"],
    explanation: "1 ₿ = 100 million satoshis. The satoshi is the smallest unit and is named after the author of the Bitcoin white paper.",
  },
  {
    id: 25,
    type: "single",
    question: "TRUE or FALSE: \"Bitcoin\" (capital B) refers to the system, \"bitcoin\" (small b) refers to the currency unit.",
    options: { a: "TRUE", b: "FALSE" },
    correct: ["a"],
    explanation: "Capital B = the Bitcoin system, small b = the currency unit.",
  },
  {
    id: 26,
    type: "multiple",
    question: "Which of the following are altcoins?",
    options: {
      a: "Litecoin",
      b: "Euro",
      c: "Ether",
      d: "US dollar",
    },
    correct: ["a", "c"],
    explanation: "An altcoin is any cryptocurrency other than Bitcoin. Euro and US dollar are fiat currencies (government-authorized money).",
  },
  {
    id: 27,
    type: "multiple",
    question: "Which statements describe an unstructured peer-to-peer network like Bitcoin's?",
    options: {
      a: "All nodes are equal, there are no \"special\" nodes",
      b: "A central server coordinates all communication",
      c: "Every node is directly connected to every other node",
      d: "All nodes are responsible for providing network services",
    },
    correct: ["a", "d"],
    explanation: "Each node is connected directly or indirectly to any other node, not necessarily directly (so c is wrong). There is no central coordinator.",
  },
  {
    id: 28,
    type: "multiple",
    question: "After a new node has connected to its first peer, what can happen next?",
    options: {
      a: "It can request further node addresses from that peer",
      b: "It must be approved by all other nodes first",
      c: "The peer can forward the new node's address to its own peers",
      d: "It automatically receives a copy of every other node's wallet",
    },
    correct: ["a", "c"],
    explanation: "Requesting addresses helps the new node find more peers. Forwarding its address makes the new node better known in the network.",
  },
  {
    id: 29,
    type: "single",
    question: "How is data propagated within the Bitcoin network?",
    options: {
      a: "The sender transmits it directly to every node",
      b: "Message flooding: each node forwards new data to its peers, which forward it on",
      c: "A central server distributes it",
      d: "Only miners forward data",
    },
    correct: ["b"],
    explanation: "Flooding gives all nodes a consistent view without any central party.",
  },
  {
    id: 30,
    type: "single",
    question: "To reduce redundant traffic, a node first announces new data by sending:",
    options: {
      a: "the complete data",
      b: "its hash value (a kind of short fingerprint)",
      c: "a digital signature of the data",
      d: "the nonce",
    },
    correct: ["b"],
    explanation: "Peers check whether they already know the hash. Only if not, they request the full data.",
  },
  {
    id: 31,
    type: "single",
    question: "Why does Bitcoin try to hide the network topology?",
    options: {
      a: "To make transactions faster",
      b: "Because the topology might allow linking Bitcoin addresses to IP addresses",
      c: "To reduce the size of the blockchain",
      d: "To prevent double spending",
    },
    correct: ["b"],
    explanation: "Users are only pseudonymous. Linking addresses to IP addresses could make users identifiable.",
  },
  {
    id: 32,
    type: "multiple",
    question: "Which techniques does Bitcoin use to hide the network topology?",
    options: {
      a: "Returning only a random subset of a peer's address list",
      b: "Forwarding data only after a randomly chosen time delay",
      c: "Forwarding data immediately to all peers",
      d: "Encrypting the blockchain",
    },
    correct: ["a", "b"],
    explanation: "The random delay prevents others from determining exactly when data reached a node.",
  },
  {
    id: 33,
    type: "single",
    question: "TRUE or FALSE: The Bitcoin blockchain only stores the current balance of each address.",
    options: { a: "TRUE", b: "FALSE" },
    correct: ["b"],
    explanation: "The blockchain stores the complete transaction history, not just balances.",
  },
  {
    id: 34,
    type: "single",
    question: "Digital signatures allow to check that the right wallet sent a transaction. What do they NOT prevent on their own?",
    options: {
      a: "A transaction being sent by a wallet that does not own the coins",
      b: "Double spending",
      c: "A transaction being modified after it was signed",
      d: "None of the above",
    },
    correct: ["b"],
    explanation: "A malicious wallet could still sign several transactions spending the same coins. This is why the full transaction history is kept.",
  },
  {
    id: 35,
    type: "multiple",
    question: "A transaction is accepted if:",
    options: {
      a: "it is authentic (really sent by the owner of the bitcoins)",
      b: "the sender does not spend bitcoins it does not have (anymore)",
      c: "it was approved by a central authority",
      d: "it was sent from a known IP address",
    },
    correct: ["a", "b"],
    explanation: "The second condition requires checking previous transactions. The inputs refer to unspent outputs of earlier transactions.",
  },
  {
    id: 36,
    type: "single",
    question: "The inputs of a transaction refer to:",
    options: {
      a: "the outputs of previous transactions (unspent coins)",
      b: "the wallet's private key",
      c: "the current block height",
      d: "the Merkle root",
    },
    correct: ["a"],
    explanation: "Coins to be spent are references to unspent outputs of earlier transactions.",
  },
  {
    id: 37,
    type: "single",
    question: "Roughly how often are transactions grouped into a new block?",
    options: {
      a: "every second",
      b: "every minute",
      c: "every 10 minutes",
      d: "every 24 hours",
    },
    correct: ["c"],
    explanation: "Each new block increases the block height by 1. The first block (height 0) is the genesis block.",
  },
  {
    id: 38,
    type: "multiple",
    question: "Which of the following are fields of the block header?",
    options: {
      a: "Previous Block Hash",
      b: "Merkle Root",
      c: "Nonce",
      d: "Sender address",
    },
    correct: ["a", "b", "c"],
    explanation: "The header contains version, previous block hash, Merkle root, timestamp, difficulty target and nonce.",
  },
  {
    id: 39,
    type: "single",
    question: "How large is the block header?",
    options: {
      a: "32 bytes",
      b: "80 bytes",
      c: "256 bytes",
      d: "variable size",
    },
    correct: ["b"],
    explanation: "4 (version) + 32 (previous block hash) + 32 (Merkle root) + 4 (timestamp) + 4 (difficulty target) + 4 (nonce) = 80 bytes.",
  },
  {
    id: 40,
    type: "single",
    question: "How does a block reference its predecessor?",
    options: {
      a: "Its Previous Block Hash field contains the double SHA-256 hash of the previous block's header",
      b: "It contains a copy of all previous transactions",
      c: "It contains the previous block's height",
      d: "It contains the previous block's timestamp",
    },
    correct: ["a"],
    explanation: "This links the blocks into a chain. Changing an old block changes its hash and breaks the link.",
  },
  {
    id: 41,
    type: "multiple",
    question: "Which statements about a hash function H: {0,1}* → {0,1}^n are true?",
    options: {
      a: "It is deterministic",
      b: "It maps inputs of arbitrary length to outputs of fixed length",
      c: "The output gets longer for longer inputs",
      d: "Hashing the same input twice can give different outputs",
    },
    correct: ["a", "b"],
    explanation: "Typical output lengths n are 256 or 512 bits.",
  },
  {
    id: 42,
    type: "multiple",
    question: "Which are the three security requirements of a cryptographic hash function?",
    options: {
      a: "Collision resistance",
      b: "Preimage resistance",
      c: "Second-preimage resistance",
      d: "Reversibility",
    },
    correct: ["a", "b", "c"],
    explanation: "A secure hash function should not be reversible, which is the point of preimage resistance.",
  },
  {
    id: 43,
    type: "single",
    question: "For an n-bit hash function, what is the effort for finding a collision?",
    options: {
      a: "O(n)",
      b: "O(2^(n/2))",
      c: "O(2^n)",
      d: "O(2^(2n))",
    },
    correct: ["b"],
    explanation: "Finding a collision is easier than finding a preimage (O(2^n)).",
  },
  {
    id: 44,
    type: "single",
    question: "In a Merkle tree with leaves x1, x2, x3, x4, how is the root computed?",
    options: {
      a: "H(x1 || x2 || x3 || x4)",
      b: "H( H(x1 || x2) || H(x3 || x4) )",
      c: "H(x1) || H(x4)",
      d: "H(x1 || x4)",
    },
    correct: ["b"],
    explanation: "Each parent node is the hash of its two child nodes. The root serves as the fingerprint of the whole set (in Bitcoin: the transactions of a block).",
  },
  {
    id: 45,
    type: "single",
    question: "To prove that x3 is contained in the set (leaves x1..x4), what must be provided in addition to x3?",
    options: {
      a: "x1 and x2",
      b: "x4 and y1",
      c: "y2 only",
      d: "the complete set",
    },
    correct: ["b"],
    explanation: "With x4 and y1, the verifier can recompute the path from x3 to the root and compare it with the known root. The full set is not needed.",
  },
  {
    id: 46,
    type: "single",
    question: "Which property of hash functions prevents a sender from preparing two different messages with the same commitment and choosing later which to reveal?",
    options: {
      a: "Collision resistance",
      b: "Preimage resistance",
      c: "Second-preimage resistance",
    },
    correct: ["a"],
    explanation: "Preimage resistance keeps the committed message secret, and second-preimage resistance prevents replacing the chosen message afterwards.",
  },
  {
    id: 47,
    type: "single",
    question: "Is the algorithm \"x mod 1337, padded to 4 digits\" a hash function? Is it a cryptographic hash function?",
    options: {
      a: "Hash function: yes, cryptographic: yes",
      b: "Hash function: yes, cryptographic: no",
      c: "Hash function: no, cryptographic: no",
    },
    correct: ["b"],
    explanation: "It is deterministic and has a fixed output length, but H(0) = H(1337) is a trivial collision, and preimages are easy to find.",
  },
  {
    id: 48,
    type: "single",
    question: "Which change requires a hardfork?",
    options: {
      a: "Tightening the rules so that previously valid blocks become invalid",
      b: "Changing the rules to allow blocks that older nodes reject",
      c: "Any change to the wallet software",
    },
    correct: ["b"],
    explanation: "A hardfork can cause a lasting chain split. In a softfork, blocks following the new rules remain valid under the old rules.",
  },
  {
    id: 49,
    type: "single",
    question: "TRUE or FALSE: Coins are stored inside the wallet.",
    options: { a: "TRUE", b: "FALSE" },
    correct: ["b"],
    explanation: "A wallet manages keys and addresses and creates or signs transactions. Coins are recorded through transactions on the blockchain.",
  },
  {
    id: 50,
    type: "text",
    question: "What component is missing from this block?",
    image: "original/missing_merkleroot.png",
    answers: ["Merkle Root", "MerkleRoot"],
    explanation: "The block header contains version, previous block hash, Merkle root, timestamp, difficulty target and nonce. The Merkle root is the fingerprint of the transactions in the block.",
  },
  {
    id: 51,
    type: "text",
    question: "What component is missing from this block?",
    image: "original/missing_nonce.png",
    answers: ["Nonce"],
    explanation: "The nonce is the field that miners change while searching for a valid block hash.",
  },
  {
    id: 52,
    type: "text",
    question: "What component is missing from this block?",
    image: "original/missing_timestamp.png",
    answers: ["Timestamp", "Time Stamp"],
    explanation: "The timestamp holds the approximate creation time of the block.",
  },
];

// ---- Helpers ----

// Ignores case and whitespace, accepts "→" as "->"
function normalizeText(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/→/g, "->");
}

// given: array of option ids (single/multiple) or a string (text)
function checkAnswer(q, given) {
  if (q.type === "text") {
    const g = normalizeText(given);
    return q.answers.some((a) => normalizeText(a) === g);
  }
  const g = [...given].sort().join(",");
  const c = [...q.correct].sort().join(",");
  return g === c;
}

if (typeof module !== "undefined") {
  module.exports = { quizData, checkAnswer, normalizeText };
}
